services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
      POSTGRES_DB: bank_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_user -d bank_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://bank_user:bank_password@postgres:5432/bank_db?sslmode=disable
      - JWT_SECRET=very_secret_key
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations  
    restart: unless-stopped

volumes:
  postgres_data: